name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necessário para obter o histórico completo para tags

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Read Version from pom.xml
        id: project_version
        run: |
          VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.6.0:exec)
          echo "::set-output name=version::$VERSION"

      - name: Build with Maven
        run: mvn package

      - name: Package with jpackage (Windows)
        shell: pwsh
        run: |
          $version = "${{ steps.project_version.outputs.version }}"
          jpackage --type exe `
                   --input target `
                   --main-jar "logicban-$version.jar" `
                   --main-class br.ufcat.logicban.ui.Main `
                   --dest target/jpackage `
                   --app-version $version `
                   --name LogicBan `
                   --vendor "Bug Hunters" `
                   --copyright "Copyright (C) 2025" `
                   --icon src/resources/assets/logos/icone.ico `
                   --win-menu `
                   --win-per-user-install `
                   --win-help-url "https://github.com/GustavoBorges13/LogicBan/wiki/Tutorial-%E2%80%90-Como-jogar" `
                   --win-update-url "https://github.com/GustavoBorges13/LogicBan/releases/latest"
      
      - name: Verify Windows artifact
        shell: pwsh
        run: |
            dir target/jpackage/
        
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: logicban-windows
          path: target/jpackage/*.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necessário para obter o histórico completo para tags

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Read Version from pom.xml
        id: project_version
        run: |
          VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.6.0:exec)
          echo "::set-output name=version::$VERSION"

      - name: Build with Maven
        run: mvn -q package -DincludeScope=compile
        
      - name: Clean jpackage output directory
        run: |
          rm -rf ./jpackage-output
          mkdir -p ./jpackage-output

      - name: Package with jpackage (Linux)
        run: |
          version="${{ steps.project_version.outputs.version }}"
          jpackage --type deb \
             --input target \
             --main-jar "logicban-$version.jar" \
             --main-class br.ufcat.logicban.ui.Main \
             --dest ./jpackage-output \
             --app-version "$version" \
             --name LogicBan \
             --vendor "Bug Hunters" \
             --copyright "Copyright (C) 2025" \
             --icon src/resources/assets/logos/icone.png \
             --linux-menu-group "Utility;" \
             --linux-shortcut \
             --linux-app-category "Utility" \
             --linux-package-name "logicban" \
             --linux-deb-maintainer "ggustavo.borges13@exemplo.com" \
             --linux-rpm-license-type "GPLv3" 

      - name: Clean up dependencies in control file
        run: |
          # Extraindo o conteúdo do pacote .deb
          version="${{ steps.project_version.outputs.version }}"
          dpkg-deb -x ./jpackage-output/logicban_${version}_amd64.deb /tmp/logicban
          dpkg-deb -e ./jpackage-output/logicban_${version}_amd64.deb /tmp/logicban/DEBIAN

          # Removendo as dependências desnecessárias do arquivo control
          sed -i '/libasound2t64/d' /tmp/logicban/DEBIAN/control
          sed -i '/libmd0/d' /tmp/logicban/DEBIAN/control
          sed -i '/libx11-6/d' /tmp/logicban/DEBIAN/control

          # Removendo o campo "Depends" se não for necessário
          sed -i '/^Depends:/d' /tmp/logicban/DEBIAN/control

          # Recriar o pacote .deb com o arquivo control modificado
          dpkg-deb -b /tmp/logicban ./jpackage-output/logicban_${version}_amd64.deb

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: logicban-linux-deb
          path: ./jpackage-output/*.deb

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necessário para obter o histórico completo para tags

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Read Version from pom.xml
        id: project_version
        run: |
          VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.6.0:exec)
          echo "::set-output name=version::$VERSION"

      - name: Build with Maven
        run: mvn package

      - name: Package with jpackage (macOS)
        run: |
          version="${{ steps.project_version.outputs.version }}"
          jpackage --type dmg \
                   --input target \
                   --main-jar "logicban-$version.jar" \
                   --main-class br.ufcat.logicban.ui.Main \
                   --dest target/jpackage \
                   --app-version "$version" \
                   --name LogicBan \
                   --vendor "Bug Hunters" \
                   --copyright "Copyright (C) 2025" \
                   --icon src/resources/assets/logos/icone.ico
    
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: logicban-macos
          path: target/jpackage/*.dmg

  upload-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permissão para criar releases e fazer upload de ativos
      actions: read    # Permissão para acessar os artefatos

    needs: [build-windows, build-linux, build-macos]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Verify downloaded artifacts
        run: |
            ls -lh ./artifacts/logicban-windows
            ls -lh ./artifacts/logicban-linux-deb
            ls -lh ./artifacts/logicban-macos

      - name: Read Version from pom.xml
        id: project_version
        run: |
          VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.6.0:exec)
          echo "::set-output name=version::$VERSION"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.project_version.outputs.version }}
          release_name: Release v${{ steps.project_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Windows artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/logicban-windows/LogicBan-${{ steps.project_version.outputs.version }}.exe
          asset_name: LogicBan-Windows.exe
          asset_content_type: application/octet-stream

      - name: Upload Linux artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/logicban-linux-deb/logicban_${{ steps.project_version.outputs.version }}_amd64.deb
          asset_name: LogicBan-Linux.deb
          asset_content_type: application/octet-stream

      - name: Upload macOS artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/logicban-macos/target/jpackage/logicban_${{ steps.project_version.outputs.version }}.dmg
          asset_name: LogicBan-macOS.dmg
          asset_content_type: application/octet-stream